services:
  blue:
    container_name: blue
    image: konkukkuit/kuitee
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - monitoring

  green:
    container_name: green
    image: konkukkuit/kuitee
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - monitoring

  discord-bot:
    container_name: discord-bot
    image: konkukkuit/kuitee-bot
    env_file:
      - .env
    environment:
      AWS_REGION: ap-northeast-2
      LOG_LEVEL: info
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true   # 이미 docker network create monitoring 으로 만들어 둘 거라 external 로 선언